# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Dude
email: chris.c.cannon@gmail.com
description:  This is my personal blog, hosted using [GitHub Pages](https://pages.github.com).
  I am a Computer Engineering undergraduate at the North Carolina Agricultural and
  Technical State University in Greensboro, North Carolina! I wanted to blog here to
  discuss all things Computer Science, engineering, and all other things that strike
  my interest. Enjoy!
baseurl: "/jekyll-wing-template" # the subpath of your site, e.g. /blog
url: "https://ccannon94.github.io" # the base hostname & protocol for your site
twitter_username: ccannon94
github_username:  ccannon94

# Build settings
markdown: kramdown
